module.exports.descriptor = [
    'Nature',
    'Mr.',
    'Taste of',
    'The Best',
    'Modern',
    'Classic',
    'Traditional',
    'Takeout',
    'Jungle',
    'Corner',
    'Sizzling',
    'Healthy',
    'Fresh',
    'Regal',
    'Fuel',
    'Recharge',
    'Fire',
    'University'
]

module.exports.categories = [
    'Juice and Smoothies',
    'Breakfast',
    'Ramen',
    'Mediterranean',
    'Indian',
    'Sandwich',
    'Salad',
    'Pasta',
    'Sushi',
    'Burgers',
    'Bubble Tea',
    'Bakery',
    'Deli',
    'Diner',
    'BBQ',
    'Viet',
    'Wings',
    'Coffee',
    'Korean',
    'Chicken',
    'Donuts'
]